hidden_dim:
learning_rate: 0.001
weight_decay: 1.e-6
nesterov: True
scheduler_type: 'warmup_cosine'
warmup_epochs: 20
gamma: 0.1
final_lr: 0
n_train: 1000
train_steps: 10000000
val_steps: 10000
optim: 'SGD'
ckpoint: 'last'