model_params:
  name: 'RecurrentEL'
  input_size: [1, 64, 64]
  architecture: 'base'
  latent_size: 10
  dictionary_size: 256
  beta: 0.0
  lr: 0.0001
  recon_loss: 'bce'

exp_params:
  dataset: dsprites90d_random_v5
  data_path: "YourPathToData"
  train_workers: 4
  val_workers: 1
  random_seed: 2001
  batch_size: 64 # Better to have a square number
  max_epochs: 100

trainer_params:
  gpus: [0, ]

logging_params:
  save_dir: "logs/"
